汉化@Test
program-in-chinese/junit4_in_chinese pull request #2
Opened 2017-08-13 08:56 UTC by azige

参考 https://github.com/program-in-chinese/junit4_in_chinese/issues/1

2017-08-13 18:42 UTC, nobodxbodon requested changes
非常感谢! 个人功力有限, 评论中定有不妥, 还请多多包涵.
希望合作愉快!

2017-08-13 18:42 UTC, nobodxbodon commented on src/main/java/com/github/program_in_chinese/junit4_in_chinese/测试.java
> + */
之前用的是LGPL(pom.xml中有声明), 请问是否觉得GPL更合适?

2017-08-13 18:42 UTC, nobodxbodon commented on src/main/java/com/github/program_in_chinese/junit4_in_chinese/测试.java
> +// TODO: 翻译 org.junit.Test 的参考文档？
同意. 留着TODO比较好. 其实断言里应该也有的. 文档需要慢慢补..

2017-08-13 18:42 UTC, nobodxbodon commented on src/main/java/com/github/program_in_chinese/junit4_in_chinese/运行器.java
> +
不好意思, 之前没考虑包路径. 
感觉也许依照原本的包结构, 把它放在另一个包里比较好. 比如"运行器"包.
不过既然现在只有一个运行器, 也许暂时不另建包也行...

2017-08-13 18:42 UTC, nobodxbodon commented on src/main/java/com/github/program_in_chinese/junit4_in_chinese/运行器.java
> +    protected void validateTestMethods(List errors){
蛋挑骨: `List<Throwable> errors`

2017-08-13 18:42 UTC, nobodxbodon commented on src/main/java/com/github/program_in_chinese/junit4_in_chinese/运行器.java
> +    protected Statement withPotentialTimeout(FrameworkMethod method,
既然原库里已经@Deprecated了, 我们还是顺势不支持它了吧? 包袱越少越好 :)

2017-08-13 18:42 UTC, nobodxbodon commented on src/main/java/com/github/program_in_chinese/junit4_in_chinese/运行器.java
> + * 当 @Test 与 @测试 同时存在时，以 @测试 优先。
暂时想象不出什么情况下需要支持@ Test和@ 测试混用... 要不先仅支持@ 测试, 如果碰到需要混用的情况再添加支持吧? 如果支持混用的话, 一些方法可能需要更多的unit test来覆盖. 比如下面这个好像通不过:
```
    @测试(期望异常 = NumberFormatException.class)
    @Test(expected = IllegalStateException.class)
    public void 期望异常的情况(){
        throw new IllegalStateException();
    }
```

2017-08-13 18:42 UTC, nobodxbodon commented on src/main/java/com/github/program_in_chinese/junit4_in_chinese/运行器.java
> +public class 运行器 extends BlockJUnit4ClassRunner{
关于类名, 之前因为想要区分类名和变量名, 个人是用"xx类"来命名. 不知有没有更好的办法?
这个代码风格问题其实可以从长计议. 如果这里不用"类"后缀, 我可以把"断言类"也改回成"断言". 这样至少一个项目内的命名保持一致.

2017-08-13 18:42 UTC, nobodxbodon commented on src/test/java/com/github/program_in_chinese/junit4_in_chinese/运行器测试类.java
> + */
顺便讨论一下pom里developers部分怎么写吧? 现在暂时用我的id, 感觉最好用个团队名称?
```
<developers>
	<developer>
	  <id>nobodxbodon</id>
	  <name></name>
	</developer>
  </developers>
```

2017-08-13 18:42 UTC, nobodxbodon commented on src/main/java/com/github/program_in_chinese/junit4_in_chinese/测试.java
> +public @interface 测试{
关于代码格式, 好像和[我用的](https://github.com/google/styleguide/blob/gh-pages/eclipse-java-google-style.xml)有点不同, 比如{前没有空格, 缩进是4(我的是2). 感觉用同样的比较方便. 不知你用的代码模板是哪个?

2017-08-13 18:52 UTC, azige commented on src/main/java/com/github/program_in_chinese/junit4_in_chinese/测试.java
> + */
我直接用了IDE的模版，可能把源文件里的声明去掉只用项目里的许可声明好了？
其实没什么特别需要的话是不是与junit保持一致用Eclipse Public License比较好（其实本人也没有特别研究过大部分这些许可的差异）

2017-08-13 18:55 UTC, azige commented on src/main/java/com/github/program_in_chinese/junit4_in_chinese/测试.java
> +public @interface 测试{
我用的略微修改过一点的NetBeans IDE默认风格（据说是基于标准JDK源代码风格）。如果需要统一代码风格的话，我记得有个maven插件Checkstyle，虽然本人也没用过，可以考虑尝试一下？

2017-08-13 18:56 UTC, azige commented on src/main/java/com/github/program_in_chinese/junit4_in_chinese/运行器.java
> +
这个可以依你决定来修改

2017-08-13 19:03 UTC, azige commented on src/main/java/com/github/program_in_chinese/junit4_in_chinese/运行器.java
> + * 当 @Test 与 @测试 同时存在时，以 @测试 优先。
之前粗略的考虑了一下兼容性问题（或者可能只是下意识的遵循里氏替换原则），例如在旧的测试类中保留原本 @Test 的代码，而新的测试用例可以用 @测试 来写。
可能比较好的方案是只要 @测试 存在就完全忽略 @Test，虽然大概没有人会刻意混用

2017-08-13 19:03 UTC, azige commented on src/main/java/com/github/program_in_chinese/junit4_in_chinese/运行器.java
> +public class 运行器 extends BlockJUnit4ClassRunner{
从长计议吧

2017-08-13 19:06 UTC, azige commented on src/main/java/com/github/program_in_chinese/junit4_in_chinese/运行器.java
> +    protected void validateTestMethods(List errors){
我记得修了一个漏了泛型参数的地方来着，但是没想通为什么会漏……明明是从junit的源码里复制过来的

2017-08-13 19:11 UTC, azige commented on src/main/java/com/github/program_in_chinese/junit4_in_chinese/运行器.java
> +    protected Statement withPotentialTimeout(FrameworkMethod method,
没找到替代方法orz，而且看起来超类里目前还是需要这个方法实现的

2017-08-13 19:17 UTC, azige commented on src/test/java/com/github/program_in_chinese/junit4_in_chinese/运行器测试类.java
> + */
<developers>下是可以写一堆<developer>的嘛，每人签个名好了 😄 

（其实那个 `@author` 也是IDE模版）

2017-08-13 19:43 UTC, nobodxbodon commented on src/main/java/com/github/program_in_chinese/junit4_in_chinese/测试.java
> +public @interface 测试{
嗯, 需要研究一下. 我新开个issue好了.

2017-08-13 19:56 UTC, nobodxbodon commented on src/main/java/com/github/program_in_chinese/junit4_in_chinese/运行器.java
> + * 当 @Test 与 @测试 同时存在时，以 @测试 优先。
嗯. 你的例子蛮合理的. 我主要的顾虑是"混用"的严格定义有点困难. 可以之后靠补全测试用例来细究.

2017-08-13 19:59 UTC, nobodxbodon commented on src/main/java/com/github/program_in_chinese/junit4_in_chinese/测试.java
> + */
有道理. 之前另一个库也是沿用原库的license的. 那应该源文件里就不用加了. 改EPL在另外提交里做好了.
BTW 你在哪个时区啊? 这么快回复挺意外的 lol

2017-08-13 20:01 UTC, nobodxbodon commented on src/main/java/com/github/program_in_chinese/junit4_in_chinese/运行器.java
> +    protected void validateTestMethods(List errors){
方便改一下吗?

2017-08-13 20:02 UTC, nobodxbodon commented on src/test/java/com/github/program_in_chinese/junit4_in_chinese/运行器测试类.java
> + */
+1. 那就顺便签个名吧? 然后我再merge.

2017-08-14 16:37 UTC, azige commented on src/main/java/com/github/program_in_chinese/junit4_in_chinese/测试.java
> + */
我在UTC+8，其实昨天在肝舰（其实今天也是）

2017-08-14 16:46 UTC, azige commented on src/main/java/com/github/program_in_chinese/junit4_in_chinese/测试.java
> +public @interface 测试{
话说一般用的缩进不都是4么 https://github.com/google/styleguide/blob/gh-pages/eclipse-java-google-style.xml#L99

2017-08-14 17:17 UTC, nobodxbodon commented on src/main/java/com/github/program_in_chinese/junit4_in_chinese/测试.java
> +public @interface 测试{
这个蛮神奇的, 我刚又确认重新导入了一下, 还是缩进2:
![screen shot 2017-08-14 at 10 15 29 am](https://user-images.githubusercontent.com/392497/29282959-a2512cb0-80d9-11e7-9e61-bdb5b3ddcecf.png)
主要我之前在G家打短工的时候他们用的也是缩进2, 所以就没觉得奇怪.

2017-08-14 17:31 UTC, nobodxbodon approved these changes
多谢! 如果你觉得OK就merge吧. 刚把你加成collaborator了. 下次我的commit也会请你review. 觉得同行互审蛮好的.

2017-08-14 17:31 UTC, nobodxbodon commented on src/main/java/com/github/program_in_chinese/junit4_in_chinese/运行器.java
> +    private Class getExpectedException(FrameworkMethod method){
这里好像缺了`<? extends Throwable>`. 我可能之后会对这里做一点改动, 因为感觉两块代码有点重复. getTimeout和possiblyExpectingExceptions也许也会.
另外, 我可能会对代码做一点中文化 :)

2017-08-14 17:41 UTC, azige commented on src/main/java/com/github/program_in_chinese/junit4_in_chinese/运行器.java
> +    private Class getExpectedException(FrameworkMethod method){
还是没想通为何会漏，莫非我之前复制的是旧版本的junit源码？

2017-08-14 17:51 UTC, nobodxbodon commented on src/main/java/com/github/program_in_chinese/junit4_in_chinese/运行器.java
> +    private Class getExpectedException(FrameworkMethod method){
你用的是https://github.com/junit-team/junit4 的master吧? 那就比较诡异了, 总不会是ide吞了吧. 
无所了, 合并吧~

2017-08-14 17:57 UTC, azige commented on src/main/java/com/github/program_in_chinese/junit4_in_chinese/运行器.java
> +    private Class getExpectedException(FrameworkMethod method){
好像我之前用的是4.10的源码，4.12里他们也修了一遍

2017-08-14 17:59 UTC, merged